[project]
name = "step-4-aunthentication-and-authorization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authx>=1.4.2",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
